# Autogenerated from /Users/caipintang/git-tmp/Advanced-Compiler/homework 1/llvm-project-17.0.2.src/clang/test/Unit/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
from pathlib import Path
def path(p):
    if not p: return ''
    return str((Path(__file__).parent / p).resolve())


import sys

config.llvm_src_root = path(r"../../../../../llvm-project-17.0.2.src/llvm")
config.llvm_obj_root = path(r"../../../..")
config.llvm_tools_dir = lit_config.substitute(path(r"../../../../bin"))
config.llvm_libs_dir = lit_config.substitute(path(r"../../../../lib"))
config.llvm_build_mode = lit_config.substitute(".")
config.clang_obj_root = path(r"../..")
config.shlibdir = lit_config.substitute(path(r"../../../../lib"))
config.target_triple = ""

# Let the main config do the real work.
lit_config.load_config(
    config, os.path.join(path(r"/Users/caipintang/git-tmp/Advanced-Compiler/homework 1/llvm-project-17.0.2.src/clang"), "test/Unit/lit.cfg.py"))
